# Generated by Django 5.2.6 on 2025-09-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemedia',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds (for video/audio)', null=True),
        ),
        migrations.AddField(
            model_name='coursemedia',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Whether this content is available as preview'),
        ),
        migrations.AlterField(
            model_name='coursemedia',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('image', 'Image'), ('audio', 'Audio'), ('other', 'Other')], max_length=20),
        ),
    ]
