# Generated by Django 5.1.4 on 2025-12-20 22:53

import courses.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemedia',
            name='file',
            field=models.FileField(storage=courses.storage.HostingerVideoStorage(), upload_to='course_media/'),
        ),
    ]
