# Generated by Django 5.1.4 on 2025-12-20 22:59

import courses.models
import courses.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_coursemedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemedia',
            name='file',
            field=models.FileField(storage=courses.storage.HostingerVideoStorage(), upload_to=courses.models.course_media_path),
        ),
    ]
