# Generated by Django 5.1.4 on 2025-12-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursemedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemedia',
            name='file',
            field=models.CharField(max_length=500),
        ),
    ]
