# Generated by Django 5.1.4 on 2025-12-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_coursemedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemedia',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration (e.g. 10:30)', max_length=20, null=True),
        ),
    ]
