# Generated by Django 5.1.4 on 2025-12-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_coursemedia_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemedia',
            name='session',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
