# Generated by Django 5.1.4 on 2025-12-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_coursemedia_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
