# Generated by Django 5.2.6 on 2025-10-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='EGP', max_length=10),
        ),
    ]
